- name: Example of  Setup in playbook 
  hosts: all
  tasks:
     - name: Storage Kernel Version into /etc/motd
       copy:
           content: "Hello your kernel version is {{ ansible_kernel }}" 
           dest: /etc/motd



     - name: 
