- hosts: all
  tasks:
    - name: install httpd
      yum:
           name: httpd
           state: installed
      notify: 
          - restart_machine
          - machine_wait
          - health_check


  handlers:
 
    - name: Reboot
      command: shutdown -r now
      async: 1
      poll: 0
      listen: restart_machine

    - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        search_regex: OpenSSH
        delay: 10
        timeout: 300
      delegate_to: localhost
      listen: machine_wait


    - debug:
           msg: "Machine up succussfully"
      listen: health_check
